### PR TITLE
Make passing child directories as bash args work

### PR DESCRIPTION
**Pull request by 0xW1sKy**
Allows end user to be in a parent directory (i.e. "One Pace") and then perform the rename task against each child directory (after loading json files from parent)

```bash
for f in ./*; do
    if [ -d "$f" ]; then
        python rename.py -d "$f"
    fi
done
```

### CODE REVIEW

**Comment by 0xW1sKy** [comment]
this is just a quick convenience item so you can run the rename.py against the entire torrent folder from it's root directory.

Step 1) copy rename.py, chapters-reference.json, and episodes-reference.json into the directory with your Arc folders

Step 2) run this in bash or something similar in your shell of choice:
```
for f in ./*; do
    if [ -d "$f" ]; then
        python rename.py -d "$f"
    fi
done
```

**Comment by Matroxt** [comment]
Hey there

Appreciate the PR.
Your PR might be a bit pointless if we merge PR #16, and I like that implementation better.
It would avoid having to loop the script with bash.

What do you think?

**Comment by Woovie** [comment]
I agree @Matroxt that just supporting subdirectories is a superior feature.

I fixed -d last night myself with this change:

```py
directory = args["directory"]
...

...
rename(f"{directory}/{file}", f"{directory}/{new_episode_name}")
```

it worked well enough to execute it one-off. But, I did have to loop it:

```sh
find -mindepth 1 -type d -iname 'Arc*' -exec python rename.py -d "{}" \;
```

**Comment by 0xW1sKy** [comment]
Oh, I don't care either way, I just did that quick change when I was using the tool and submitted it back in case others found it helpful. whatever you think is best :)

**Comment by Matroxt** [comment]
Closing because PR #16 got merged

**Pull request closed without merging**
